// Folder Buddies — connection code ("hash") encode/decode.
//
// Human-readable format (words + grouped digits), e.g.
//   ocean-tiger-...-violet--192-168-001-005--54321--cool-folder
//   └─ 16 words = the auto-generated password ─┘  └ ip ┘ └port┘ └ folder ┘
// For IPv6 the address is shown as eight 4-hex groups instead of four decimals.
//
// The password is generated by the computer and lives *inside* the code — there
// is no user-chosen password. Treat the whole code as a secret.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace fb {

struct Token {
    std::string ip;                  // literal IPv4 or IPv6 to connect to
    uint16_t port = 0;
    std::vector<uint8_t> secret;     // auto-generated password / bearer credential
    std::string folder;              // human-readable folder name (shown verbatim)

    std::string encode() const;
    static bool decode(const std::string& s, Token& out);
};

// Data-path session secret length. 32 bytes keeps the filesystem encryption
// independent from the Cloudflare room password and gives the transport a full
// 256-bit bearer secret after the encrypted room payload is decrypted.
constexpr size_t kSecretBytes = 32;

// n random bytes from the OS CSPRNG.
std::vector<uint8_t> random_bytes(size_t n);

} // namespace fb
